# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'portfolioApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for portfolioApp
  # add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Unbox'
pod 'Wrap'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'LocationManagerSwift'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end
